# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'amcp_test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 3, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.f_center = QtWidgets.QLineEdit(self.groupBox)
        self.f_center.setObjectName("f_center")
        self.gridLayout_4.addWidget(self.f_center, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.f_min = QtWidgets.QLineEdit(self.groupBox)
        self.f_min.setObjectName("f_min")
        self.gridLayout_4.addWidget(self.f_min, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.f_max = QtWidgets.QLineEdit(self.groupBox)
        self.f_max.setObjectName("f_max")
        self.gridLayout_4.addWidget(self.f_max, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_vna = QtWidgets.QComboBox(self.groupBox_6)
        self.select_vna.setObjectName("select_vna")
        self.select_vna.addItem("")
        self.select_vna.addItem("")
        self.horizontalLayout_2.addWidget(self.select_vna)
        self.gridLayout_2.addWidget(self.groupBox_6, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_run_measurement = QtWidgets.QPushButton(self.tab)
        self.btn_run_measurement.setObjectName("btn_run_measurement")
        self.gridLayout_3.addWidget(self.btn_run_measurement, 2, 0, 1, 1)
        self.btn_run_estimation = QtWidgets.QPushButton(self.tab)
        self.btn_run_estimation.setObjectName("btn_run_estimation")
        self.gridLayout_3.addWidget(self.btn_run_estimation, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.L1_res = QtWidgets.QLabel(self.groupBox_2)
        self.L1_res.setMinimumSize(QtCore.QSize(50, 0))
        self.L1_res.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.L1_res.setObjectName("L1_res")
        self.gridLayout.addWidget(self.L1_res, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.C0_res = QtWidgets.QLabel(self.groupBox_2)
        self.C0_res.setMinimumSize(QtCore.QSize(50, 0))
        self.C0_res.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.C0_res.setObjectName("C0_res")
        self.gridLayout.addWidget(self.C0_res, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.R1_res = QtWidgets.QLabel(self.groupBox_2)
        self.R1_res.setMinimumSize(QtCore.QSize(50, 0))
        self.R1_res.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.R1_res.setObjectName("R1_res")
        self.gridLayout.addWidget(self.R1_res, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.C1_res = QtWidgets.QLabel(self.groupBox_2)
        self.C1_res.setMinimumSize(QtCore.QSize(50, 0))
        self.C1_res.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.C1_res.setObjectName("C1_res")
        self.gridLayout.addWidget(self.C1_res, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 160))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.model = QtWidgets.QLabel(self.groupBox_3)
        self.model.setMinimumSize(QtCore.QSize(0, 0))
        self.model.setStyleSheet("")
        self.model.setScaledContents(True)
        self.model.setAlignment(QtCore.Qt.AlignCenter)
        self.model.setObjectName("model")
        self.verticalLayout_2.addWidget(self.model)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphWidget = PlotWidget(self.groupBox_8)
        self.graphWidget.setObjectName("graphWidget")
        self.verticalLayout_4.addWidget(self.graphWidget)
        self.gridLayout_2.addWidget(self.groupBox_8, 1, 1, 3, 3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.python3_path = QtWidgets.QLineEdit(self.groupBox_7)
        self.python3_path.setObjectName("python3_path")
        self.gridLayout_7.addWidget(self.python3_path, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setMinimumSize(QtCore.QSize(200, 0))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox_7)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_7.addWidget(self.toolButton_5, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_5.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_5.addWidget(self.toolButton, 3, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_5.addWidget(self.toolButton_3, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setMinimumSize(QtCore.QSize(200, 0))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_6.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setMinimumSize(QtCore.QSize(200, 0))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_6.addWidget(self.toolButton_4, 2, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_6.addWidget(self.lineEdit_5, 3, 1, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_6.addWidget(self.toolButton_2, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.logfile = QtWidgets.QPlainTextEdit(self.tab_2)
        self.logfile.setObjectName("logfile")
        self.verticalLayout_5.addWidget(self.logfile)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(1)
        font.setKerning(True)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuFile.addAction(self.actionTest)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.btn_run_measurement.clicked.connect(MainWindow.run_measurement)
        self.btn_run_estimation.clicked.connect(MainWindow.run_estimation)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AMCP - Automated Measurement of Crystal Parameters"))
        self.groupBox.setTitle(_translate("MainWindow", "Crystal Specs"))
        self.label_18.setText(_translate("MainWindow", "[Hz]"))
        self.label_19.setText(_translate("MainWindow", "[Hz]"))
        self.label_17.setText(_translate("MainWindow", "[Hz]"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>F<span style=\" vertical-align:sub;\">center</span></p></body></html>"))
        self.f_center.setText(_translate("MainWindow", "26E6"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>F<span style=\" vertical-align:sub;\">min</span></p></body></html>"))
        self.f_min.setText(_translate("MainWindow", "25E6"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>F<span style=\" vertical-align:sub;\">max</span></p></body></html>"))
        self.f_max.setText(_translate("MainWindow", "27E6"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Select VNA"))
        self.select_vna.setItemText(0, _translate("MainWindow", "MiniVNA"))
        self.select_vna.setItemText(1, _translate("MainWindow", "NanoVNA"))
        self.btn_run_measurement.setText(_translate("MainWindow", "Run Measurement"))
        self.btn_run_estimation.setText(_translate("MainWindow", "Run Estimation"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Results"))
        self.label_9.setText(_translate("MainWindow", "L1:"))
        self.L1_res.setText(_translate("MainWindow", "-"))
        self.label_15.setText(_translate("MainWindow", "[mH]"))
        self.label_10.setText(_translate("MainWindow", "R1:"))
        self.label_16.setText(_translate("MainWindow", "[Ω]"))
        self.label_4.setText(_translate("MainWindow", "C0:"))
        self.label_14.setText(_translate("MainWindow", "[fF]"))
        self.label_5.setText(_translate("MainWindow", "C1:"))
        self.C0_res.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "[pF]"))
        self.R1_res.setText(_translate("MainWindow", "-"))
        self.C1_res.setText(_translate("MainWindow", "-"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Crystal Model"))
        self.model.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/crystal/images/xtal_model.png\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Overview"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Python"))
        self.label_24.setText(_translate("MainWindow", "Python 3 Interpreter:"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.groupBox_4.setTitle(_translate("MainWindow", "MiniVNA"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.label_20.setText(_translate("MainWindow", "Calibration File:"))
        self.pushButton_3.setText(_translate("MainWindow", "VnaJ"))
        self.groupBox_5.setTitle(_translate("MainWindow", "NanoVNA"))
        self.label_22.setText(_translate("MainWindow", "NanoVNA wrapper:"))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.label_23.setText(_translate("MainWindow", "Calibration File:"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Setup"))
        self.logfile.setPlainText(_translate("MainWindow", "start log:\n"
"--------------------\n"
""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionClose.setText(_translate("MainWindow", "Exit"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionTest.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))

from pyqtgraph import PlotWidget
import python3.gui.resource_rc
